const members = [
    {
        id: 1,
        name: "Prathis Upadhyay",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Department Head | 3rd Year Mech",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    },
    {
        id: 2,
        name: "Abhishek",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Department Head | 3rd Year Mech",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    },
    {
        id: 3,
        name: "Aryan Jangid",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Member | 2rd Year AIDS",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    },
    {
        id: 1,
        name: "Prathis Upadhyay",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Department Head | 3rd Year Mech",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    },
    {
        id: 2,
        name: "Abhishek",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Department Head | 3rd Year Mech",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    },
    {
        id: 3,
        name: "Aryan Jangid",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Member | 2rd Year AIDS",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    }, {
        id: 1,
        name: "Prathis Upadhyay",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Department Head | 3rd Year Mech",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    },
    {
        id: 2,
        name: "Abhishek",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Department Head | 3rd Year Mech",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    },
    {
        id: 3,
        name: "Aryan Jangid",
        imgURL: "https://media-exp1.licdn.com/dms/image/C5603AQFt57LxoWB0bw/profile-displayphoto-shrink_100_100/0/1590076597636?e=1647475200&v=beta&t=pQQY1rHMDgsxc3p3MkqII2KafYXgLBMvqyRsKNsxBgg",
        branch: "Member | 2rd Year AIDS",
        linkedinURL: "https://www.linkedin.com/in/prathisupadhyay/",
        instagramURl: "https://www.linkedin.com/in/prathisupadhyay/",
    }

]
export default members